# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launchwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(263, 262)
        self.signUpButton = QtWidgets.QPushButton(Form)
        self.signUpButton.setGeometry(QtCore.QRect(150, 210, 89, 25))
        self.signUpButton.setObjectName("signUpButton")
        self.from_id = QtWidgets.QLineEdit(Form)
        self.from_id.setGeometry(QtCore.QRect(80, 50, 51, 21))
        self.from_id.setObjectName("from_id")
        self.to_id = QtWidgets.QLineEdit(Form)
        self.to_id.setGeometry(QtCore.QRect(170, 50, 51, 25))
        self.to_id.setObjectName("to_id")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 41, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 50, 31, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 41, 20))
        self.label_3.setObjectName("label_3")
        self.email = QtWidgets.QLineEdit(Form)
        self.email.setGeometry(QtCore.QRect(100, 100, 121, 21))
        self.email.setObjectName("email")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 130, 51, 20))
        self.label_4.setObjectName("label_4")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(100, 130, 121, 21))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.answer = QtWidgets.QLineEdit(Form)
        self.answer.setGeometry(QtCore.QRect(100, 160, 121, 21))
        self.answer.setEchoMode(QtWidgets.QLineEdit.Password)
        self.answer.setObjectName("answer")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 160, 51, 20))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.signUpButton.setText(_translate("Form", "Launch"))
        self.label.setText(_translate("Form", "from"))
        self.label_2.setText(_translate("Form", "to"))
        self.label_3.setText(_translate("Form", "EMAIL"))
        self.label_4.setText(_translate("Form", "Password"))
        self.label_5.setText(_translate("Form", "Answer"))
